name: freetube-snap
base: core22
version: 0.18.0
summary: Free & Open Source Youtube Client.
description: |
  Freetube is a Electron Based FLOSS Youtube Client.
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

apps:
  freetube-snap:
    command: opt/FreeTube/freetube --no-sandbox --disable-seccomp-filter-sandbox
    extensions: [gnome]
    common-id: io.freetubeapp.FreeTube
    desktop: usr/share/applications/freetube.desktop   
    environment:
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - audio-playback
      - network
      - network-bind
      - network-status
      - browser-support
      - shmem
      - unity7
      - removable-media
      - screen-inhibit-control
    slots:
      - mpris
      
plugs:
  shmem:
    interface: shared-memory
    private: true
    
slots:
  mpris:
    interface: mpris
    name: chromium
  freetube-snap:
    interface: dbus
    bus: session
    name: io.freetubeapp.FreeTube

parts:
  freetube:
    source: https://github.com/FreeTubeApp/FreeTube.git
    plugin: dump
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0 | cut -c 2-)
      VER="$(git describe --tags --abbrev=0 | cut -c 2-)"
      curl -LO https://github.com/FreeTubeApp/FreeTube/releases/download/v${VER}-beta/freetube_${VER}_amd64.deb
     
    #https://github.com/FreeTubeApp/FreeTube/releases/download/v0.18.0-beta/freetube_0.18.0_amd64.deb
