name: freetube-snap
base: core22
version: 'v0.18.0'
summary: Free & Open Source Youtube Client.
description: |
  Freetube is a Electron Based FLOSS Youtube Client.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
                
apps:
  freetube-snap:
    command: opt/FreeTube/freetube --no-sandbox --disable-seccomp-filter-sandbox
    extensions: [gnome]
    environment: 
            GTK_USE_PORTAL: "1"
            TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - audio-playback
      - network
      - raw-usb
      - shmem
      - removable-media
      - unity7
      - screen-inhibit-control
    
    slots:
      - mpris
    
plugs:
  shmem:
    interface: shared-memory
    private: true
  
parts:
  freetube:
    source: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.18.0-beta/freetube_0.18.0_amd64.deb
    plugin: dump
    override-pull: |
      set -eu
      craftctl default
      chmod 0755 ./opt/FreeTube/chrome-sandbox
   #sed -i 's|Icon=brave-browser|Icon=/opt/brave.com/brave/product_logo_128\.png|g' usr/share/applications/brave-browser.desktop
   #rm -rf usr/share/applications/freetube.desktop
