name: freetube-snap
base: core22
version: 'v0.18.0'
summary: Free & Open Source Youtube Client.
description: |
  Freetube is a Electron Based FLOSS Youtube Client.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
                
apps:
  freetube-snap:
    command: usr/bin/freetube
    extensions: [gnome]
    common-id: snap.community.freetube
    environment: 
            GTK_USE_PORTAL: 1
    plugs:
      - home
      - audio-playback
      - network
      - raw-usb
      - removable-media
      - unity7
      - screen-inhibit-control
      
 
 
      
parts:
  freetube:
    source: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.18.0-beta/freetube_0.18.0_amd64.deb
    plugin: dump
   
