name: freetube-snap
base: core22
version: 'v0.18.0'
summary: Free & Open Source Youtube Client.
description: |
  Freetube is a Electron Based FLOSS Youtube Client.
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
    build-for: amd64
                
apps:
  freetube-snap:
    command: opt/FreeTube/freetube --no-sandbox --disable-seccomp-filter-sandbox
    extensions: [gnome]
    environment:
            TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - home
      - audio-playback
      - network
      - network-bind
      - browser-support
      - network-status
      - raw-usb
      - shmem
      - removable-media
      - ubuntu-download-manager
      - screen-inhibit-control

slots:
  mpris:
    interface: mpris
    name: org.mpris.MediaPlayer2.freetube
plugs:
  shmem:
    interface: shared-memory
    private: true

parts:
  freetube:
    source: https://github.com/FreeTubeApp/FreeTube/releases/download/v$SNAPCRAFT_PROHECT_VERSION-beta/freetube_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    plugin: dump

